<?php if ($this->isReady()): ?>
    <script type="text/javascript">var scr=document.createElement('script');scr.src=('https:'==document.location.protocol?'https://':'http://')+'ssl.ceneo.pl/shops/sw.js?accountGuid=<?php echo $this->getCeneoUserGuid() ?>';scr.type='text/javascript';document.getElementsByTagName('head')[0].appendChild(scr);</script>

    <noscript><a href="http://www.ceneo.pl/11817-0a" rel="nofollow" target="_blank">Opinie o Nas</a></noscript>
<?php endif ?>
