<div class="page-title">
    <h1><?php echo $this->__('Your order has been received.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php if ($this->getOrderId()):?>
<?php if ($this->getCanViewOrder()) :?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>
    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
<?php endif;?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
        <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
        <?php echo $this->getChildHtml() ?>
    </p>
<?php endif;?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>

<?php
    $ceneo_params = $this->getCeneoParams();
?>
<div class="buttons-set">

    <?php if ($ceneo_params->is_ready): ?>
        <div class="form-list">
            <div class="control">
                <div class="input-box">
                    <input type="checkbox" id="ceneo_email_conf" class="js-ceneo-email-conf checkbox" checked="checked" name="ceneo_email_conf" />
                </div>
                <label for="ceneo_email_conf"><?php echo $ceneo_params->allowSendEmailMessage ?></label>
            </div>
        </div>
    <?php endif ?>

    <button type="button" class="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>
<?php if ($ceneo_params->is_ready): ?>
    <script>
        (function(ceneoOptions) {
            var $ceneoEmailConf = jQuery('.js-ceneo-email-conf');
            
            window['ceneo_client_email'] = $ceneoEmailConf.is(':checked') ? ceneoOptions.clientEmail : '';
            window['ceneo_shop_product_ids'] = ceneoOptions.productIds;
            window['ceneo_order_id'] = ceneoOptions.orderId;
            window['ceneo_work_days_to_send_questionnaire'] = ceneoOptions.questionnaireDelayDays;

            $ceneoEmailConf.on('change', function() {
                window['ceneo_client_email'] = this.checked ? ceneoOptions.clientEmail : '';
            });
        }({
            clientEmail: '<?php echo $ceneo_params->client_email ?>',
            productIds: '<?php echo $ceneo_params->shop_product_ids ?>',
            orderId: '<?php echo $ceneo_params->order_id ?>',
            questionnaireDelayDays: <?php echo $ceneo_params->work_days_to_send_questionnaire ?>
        }));
    </script>
    <script type="text/javascript" src="https://ssl.ceneo.pl/transactions/track/v2/script.js?accountGuid=<?php echo $ceneo_params->ceneo_guid ?>"> </script>
<?php endif ?>
